import type { Card } from "../game/types";

export const cards: Card[] = [
  {
    id: "awakening-first-night",
    phase: "awakening",
    start: true,
    title: "第一夜",
    body: "你只是想做一个很小的工具，AI 在 17 分钟内给了你一个能跑的演示版本。屏幕亮着，你第一次觉得这事可能真的能做出来。",
    choices: [
      {
        id: "share-demo",
        label: "立刻发给朋友",
        effects: { momentum: 10, judgment: -4, agency: -2 },
        immediateLine: "朋友回了三个感叹号，你获得第一次外部多巴胺。",
        addFlags: ["demo-first"],
        addTraces: [{ type: "reputation", text: "第一次把演示版本发给朋友。" }],
      },
      {
        id: "read-code",
        label: "先看一遍代码",
        effects: { judgment: 9, agency: 5, momentum: -2 },
        immediateLine:
          "你发现有个变量叫 final_final_reallyFinal，但它确实能跑。",
        addFlags: ["read-first-code"],
        addTraces: [{ type: "habit", text: "开始在兴奋之后补一遍理解。" }],
      },
    ],
  },
  {
    id: "awakening-world-class-prompt",
    phase: "awakening",
    title: "世界级提示词",
    body: "你写出了一段“你是世界级全栈工程师”的提示词，并觉得它可能值 199 美元。AI 的回复看起来确实更自信了。",
    choices: [
      {
        id: "sell-prompt",
        label: "整理成模板",
        effects: { momentum: 8, judgment: -3, agency: -3 },
        immediateLine: "模板越写越长，你越看越想开一个专栏。",
        addFlags: ["prompt-template"],
        addTraces: [{ type: "work", text: "一份看起来很贵的万能提示词。" }],
      },
      {
        id: "define-output",
        label: "先写清楚验收标准",
        effects: { judgment: 10, agency: 4, momentum: -1 },
        immediateLine: "AI 没有变神，但你终于知道什么叫做完成。",
        addFlags: ["acceptance-criteria"],
        addTraces: [{ type: "habit", text: "开始给需求写验收标准。" }],
      },
    ],
  },
  {
    id: "awakening-new-tool",
    phase: "awakening",
    title: "新工具发布",
    body: "一个新工具在时间线上刷屏，宣传语写着“重新定义创造”。你当前项目刚跑通，环境还热着。",
    choices: [
      {
        id: "migrate-now",
        label: "马上迁移过去",
        effects: { momentum: 5, judgment: -7, agency: -4, stability: -3 },
        immediateLine: "你拥有了新界面，也拥有了三份新的环境变量说明。",
        addFlags: ["tool-migration"],
        addTraces: [{ type: "work", text: "一个还没命名的新工具测试项目。" }],
      },
      {
        id: "finish-current",
        label: "先完成当前版本",
        effects: { judgment: 8, stability: 6, agency: 4 },
        immediateLine: "你少了一个诱惑，当前版本多了一点进度。",
        addFlags: ["finish-current"],
        addTraces: [{ type: "habit", text: "新工具发布时没有立刻搬家。" }],
      },
    ],
  },
  {
    id: "awakening-demo-polish",
    phase: "awakening",
    title: "演示很丝滑",
    body: "核心逻辑还有点绕，但界面已经能录出一段很好看的 42 秒视频。你知道它还没真正接受过现场测试。",
    choices: [
      {
        id: "record-first",
        label: "先录，趁热发",
        effects: { momentum: 11, judgment: -8, stability: -2 },
        immediateLine: "视频很顺，产品本人暂时没有被点破。",
        addFlags: ["demo-first", "public-video"],
        addTraces: [{ type: "reputation", text: "一条看起来已经完成的录屏。" }],
      },
      {
        id: "test-flow",
        label: "找人现场点一遍",
        effects: { judgment: 9, stability: 5, momentum: -3 },
        immediateLine: "测试用户第一步就卡住了，幸好现在还不是发布会。",
        addFlags: ["tested-with-human"],
        addTraces: [
          { type: "relation", text: "一个真实用户帮你踩了第一颗雷。" },
        ],
      },
    ],
  },
  {
    id: "awakening-tiny-scope",
    phase: "awakening",
    title: "范围突然变大",
    body: "你本来只想做一个小工具，现在脑子里已经出现了平台、社区、插件市场和企业版。",
    choices: [
      {
        id: "make-platform",
        label: "顺便做成平台",
        effects: { momentum: 7, judgment: -8, stability: -5 },
        immediateLine: "路线图变得壮观，第一版变得很远。",
        addFlags: ["scope-platform"],
        addTraces: [{ type: "work", text: "一张过于宏大的路线图。" }],
      },
      {
        id: "cut-scope",
        label: "砍到一个入口",
        effects: { judgment: 10, agency: 4, stability: 4, momentum: -2 },
        immediateLine: "你删掉了五个功能，项目第一次能被一句话说清楚了。",
        addFlags: ["cut-scope"],
        addTraces: [{ type: "work", text: "一个小到能解释清楚的版本。" }],
      },
    ],
  },
  {
    id: "response-first-user",
    phase: "response",
    title: "第一个真实用户",
    body: "一个你不认识的人真的开始用了。他夸了你三句，然后提出了一个完全不在你设想里的用法。",
    choices: [
      {
        id: "listen-user",
        label: "追问他怎么用",
        effects: { judgment: 9, agency: 3, stability: 3 },
        immediateLine: "你听完以后删掉了一个炫技功能，入口反而更清楚了。",
        addFlags: ["talked-to-users"],
        addTraces: [
          { type: "relation", text: "第一次认真追问真实用户的用法。" },
        ],
      },
      {
        id: "use-praise",
        label: "把夸奖做成海报",
        effects: { momentum: 8, judgment: -5, agency: -2 },
        immediateLine: "海报很有说服力，那个真正的问题暂时还躺在聊天记录里。",
        addFlags: ["praise-poster"],
        addTraces: [
          { type: "reputation", text: "一张来自真实用户夸奖的宣传图。" },
        ],
      },
    ],
  },
  {
    id: "response-bill-arrives",
    phase: "response",
    title: "账单来了",
    body: "后台账单刷新了三次。用户在增长，调用量也在增长，免费额度看起来撑不了太久。",
    choices: [
      {
        id: "ignore-cost",
        label: "继续放开使用",
        effects: { momentum: 8, stability: -12, judgment: -5 },
        immediateLine: "用户继续进来，账单也继续跟着进来。",
        addFlags: ["cost-ignored"],
        addTraces: [{ type: "cost", text: "一张让你反复刷新的 API 账单。" }],
      },
      {
        id: "add-limits",
        label: "加缓存和限额",
        effects: { judgment: 8, stability: 8, momentum: -3 },
        immediateLine: "你第一次觉得成本控制也是产品功能。",
        addFlags: ["cost-controlled"],
        addTraces: [
          { type: "work", text: "缓存、限额和一个不那么浪漫的套餐页。" },
        ],
      },
    ],
  },
  {
    id: "response-boss-notices",
    phase: "response",
    title: "老板发现了",
    body: "你两小时做完了一周的活。老板没有问你怎么做到的，只是把一个更模糊的需求转发给你。",
    choices: [
      {
        id: "accept-vague",
        label: "接下所有模糊需求",
        effects: { momentum: 9, stability: -8, agency: -5 },
        immediateLine: "你获得了信任，也获得了更多无法验收的任务。",
        addFlags: ["vague-workload"],
        addTraces: [{ type: "relation", text: "同事开始把模糊需求都递给你。" }],
      },
      {
        id: "clarify-vague",
        label: "先写边界和验收",
        effects: { judgment: 10, agency: 6, momentum: -2 },
        immediateLine: "你没有显得更快，但需求第一次停在了可验收的范围里。",
        addFlags: ["clarified-work"],
        addTraces: [{ type: "habit", text: "开始把模糊需求拆成边界和验收。" }],
      },
    ],
  },
  {
    id: "response-public-thread",
    phase: "response",
    title: "教程火了",
    body: "你写了一条复盘帖，评论区开始催更：教程、模板、社群、付费分享，一个都没有迟到。",
    choices: [
      {
        id: "build-persona",
        label: "开始经营方法论",
        effects: { momentum: 8, agency: -5, judgment: -4 },
        immediateLine: "标题比产品更稳定，评论区比用户更热闹。",
        addFlags: ["public-methodology"],
        addTraces: [
          { type: "reputation", text: "一条被收藏很多次的方法论长帖。" },
        ],
      },
      {
        id: "ship-before-thread",
        label: "先把产品修稳",
        effects: { judgment: 7, stability: 6, momentum: -3 },
        immediateLine: "你错过了一点热度，换来了一个少报错的周一。",
        addFlags: ["ship-before-teach"],
        addTraces: [{ type: "work", text: "一个修掉关键报错的稳定版本。" }],
      },
    ],
  },
  {
    id: "response-auto-summary",
    phase: "response",
    title: "自动总结反馈",
    body: "用户反馈越来越多。你可以逐条读，也可以让 AI 自动归类、打标签、生成路线图。",
    choices: [
      {
        id: "auto-everything",
        label: "全部交给自动化",
        effects: { momentum: 9, agency: -12, judgment: -4 },
        immediateLine: "路线图很整齐，你已经不太记得原文里的人怎么说了。",
        addFlags: ["auto-everything"],
        addTraces: [{ type: "habit", text: "用户反馈开始由系统替你阅读。" }],
      },
      {
        id: "read-samples",
        label: "先读十条原文",
        effects: { judgment: 8, agency: 6, stability: 2 },
        immediateLine: "十条原文不如图表整齐，但问题更具体。",
        addFlags: ["read-user-raw"],
        addTraces: [{ type: "relation", text: "你保留了一部分用户原话。" }],
      },
    ],
  },
  {
    id: "identity-full-time",
    phase: "identity",
    title: "要不要全职",
    body: "产品有了收入，也有了问题。你开始想：这是不是那个可以改变人生的窗口期？",
    choices: [
      {
        id: "go-full-time",
        label: "宣布全职冲刺",
        effects: { momentum: 12, stability: -10, agency: 2 },
        immediateLine: "公开承诺很热血，你的日历很快被任务填满。",
        addFlags: ["full-time-promise"],
        addTraces: [{ type: "reputation", text: "一次公开的全职冲刺宣言。" }],
      },
      {
        id: "keep-runway",
        label: "先算能撑多久",
        effects: { judgment: 9, stability: 8, momentum: -3 },
        immediateLine: "你没有马上辞职，但知道接下来几个月每笔钱怎么用。",
        addFlags: ["runway-checked"],
        addTraces: [{ type: "cost", text: "一张算过未来几个月的现金流表。" }],
      },
    ],
  },
  {
    id: "identity-enterprise",
    phase: "identity",
    title: "企业版来了",
    body: "一个潜在客户问：能不能加权限、审计、团队空间和专属部署？你听见了收入，也听见了工期。",
    choices: [
      {
        id: "promise-enterprise",
        label: "直接承诺企业版",
        effects: { momentum: 8, stability: -8, judgment: -4 },
        immediateLine: "你拿到了一个大机会，也拿到了一串每天追进度的需求。",
        addFlags: ["enterprise-promised", "paid-users"],
        addTraces: [
          { type: "relation", text: "一个开始要求企业版的真实客户。" },
        ],
      },
      {
        id: "pilot-first",
        label: "先做小范围试点",
        effects: { judgment: 8, stability: 5, agency: 4 },
        immediateLine: "客户没有被激情冲昏头，你也没有。",
        addFlags: ["enterprise-pilot", "paid-users"],
        addTraces: [{ type: "work", text: "一个边界清楚的企业试点。" }],
      },
    ],
  },
  {
    id: "identity-ai-managers",
    phase: "identity",
    title: "AI 管理 AI",
    body: "你搭了三个 AI 助手：一个提需求，一个拆任务，一个总结前两个为什么吵架。",
    choices: [
      {
        id: "more-agents",
        label: "再加一个调度助手",
        effects: { momentum: 8, agency: -14, judgment: -3 },
        immediateLine: "会议纪要自动生成了，只差一个真正拍板的人。",
        addFlags: ["ai-managers"],
        addTraces: [{ type: "work", text: "一个会自动复盘自己的 AI 小组织。" }],
      },
      {
        id: "human-decision",
        label: "自己写最终决策",
        effects: { agency: 9, judgment: 5, momentum: -2 },
        immediateLine: "系统安静了一点，你终于又听见了自己的判断。",
        addFlags: ["human-decides"],
        addTraces: [{ type: "habit", text: "关键决策重新回到你手里。" }],
      },
    ],
  },
  {
    id: "identity-sleep",
    phase: "identity",
    title: "连续第七晚",
    body: "产品每天都在前进，你的睡眠记录连续几天少得很明显。朋友问周末见不见，你看了一眼待办。",
    choices: [
      {
        id: "skip-sleep",
        label: "再冲一个晚上",
        effects: { momentum: 8, stability: -14, judgment: -3 },
        immediateLine: "你修掉了一个 bug，也把自己放进了待修列表。",
        addFlags: ["body-offline"],
        addTraces: [
          { type: "habit", text: "连续深夜把自己当成不用维护的服务器。" },
        ],
      },
      {
        id: "sleep-now",
        label: "关机去睡",
        effects: { stability: 12, judgment: 4, momentum: -4 },
        immediateLine: "这个选择没有截图价值，但明天的你会感谢它。",
        addFlags: ["slept"],
        addTraces: [{ type: "habit", text: "在深夜选择关机。" }],
      },
    ],
  },
  {
    id: "identity-price",
    phase: "identity",
    title: "第一次定价",
    body: "有人问多少钱。你打开输入框，突然发现产品问题已经变成了人生问题。",
    choices: [
      {
        id: "free-forever",
        label: "先免费涨起来",
        effects: { momentum: 7, stability: -7, judgment: -4 },
        immediateLine: "用户增长了，账单也没有表现出同理心。",
        addFlags: ["free-growth"],
        addTraces: [{ type: "cost", text: "一段没有价格但很有成本的增长。" }],
      },
      {
        id: "charge-small",
        label: "收一个小价格",
        effects: { judgment: 6, stability: 7, agency: 3 },
        immediateLine: "增长慢了一点，但每个留下来的人都更值得追问。",
        addFlags: ["paid-users"],
        addTraces: [{ type: "cost", text: "第一笔小额收入和一次真正的筛选。" }],
      },
    ],
  },
  {
    id: "identity-quiet-validation",
    phase: "identity",
    title: "没有热搜的一周",
    body: "这一周没有爆款内容，没有新工具迁移，只有几个用户、一堆小修改和一个越来越清楚的入口。",
    choices: [
      {
        id: "keep-validating",
        label: "继续问用户",
        effects: { judgment: 9, stability: 6, agency: 5, momentum: -2 },
        immediateLine: "热搜没有看见你，真实用户看见了那个终于好用的按钮。",
        addFlags: ["quiet-validation"],
        addTraces: [{ type: "work", text: "一个用户不多但反馈具体的小产品。" }],
      },
      {
        id: "make-noise",
        label: "发一波产品帖",
        effects: { momentum: 8, judgment: -4, agency: -2 },
        immediateLine: "关注变多了，没修好的问题也被更多人看见。",
        addFlags: ["make-noise"],
        addTraces: [
          { type: "reputation", text: "一次比产品本身更热闹的发布。" },
        ],
      },
    ],
  },
  {
    id: "awakening-copy-paste",
    phase: "awakening",
    title: "复制来的胜利",
    body: "AI 给了你一段看起来很完整的代码。你复制、运行、成功了。唯一的问题是，你不知道它为什么成功。",
    choices: [
      {
        id: "ship-unknown",
        label: "先发，能跑就行",
        effects: { momentum: 9, judgment: -8, agency: -5 },
        immediateLine: "你获得了一个能跑的版本，也获得了一段不敢碰的代码。",
        addFlags: ["unknown-code"],
        addTraces: [{ type: "work", text: "一段能跑但没人敢改的核心逻辑。" }],
      },
      {
        id: "ask-explain",
        label: "让它逐行解释",
        effects: { judgment: 9, agency: 6, momentum: -2 },
        immediateLine: "解释没有让你变慢，反而让下一次修改少了一点玄学。",
        addFlags: ["asked-explain"],
        addTraces: [{ type: "habit", text: "开始要求 AI 解释到自己能复述。" }],
      },
    ],
  },
  {
    id: "awakening-friend-question",
    phase: "awakening",
    title: "朋友的问题",
    body: "朋友看完演示，问了一句：“这个到底给谁用？”你突然发现自己准备了 4 个技术亮点，但没有准备答案。",
    choices: [
      {
        id: "answer-with-features",
        label: "继续解释功能",
        effects: { momentum: 5, judgment: -5, agency: -2 },
        immediateLine: "功能越讲越多，对方越不确定自己是不是目标用户。",
        addFlags: ["feature-answer"],
        addTraces: [
          { type: "relation", text: "一次用功能列表回答用户是谁的对话。" },
        ],
      },
      {
        id: "name-user",
        label: "写下具体用户",
        effects: { judgment: 9, agency: 4, stability: 2 },
        immediateLine: "项目突然小了一圈，也清楚了一圈。",
        addFlags: ["named-user"],
        addTraces: [{ type: "work", text: "一个终于被写清楚的目标用户。" }],
      },
    ],
  },
  {
    id: "awakening-todo-overflow",
    phase: "awakening",
    title: "待办爆炸",
    body: "你让 AI 帮你规划下一步，它生成了 37 个任务、6 个模块和一张看起来像创业公司季度计划的表。",
    choices: [
      {
        id: "accept-plan",
        label: "照单全收",
        effects: { momentum: 7, stability: -6, judgment: -5 },
        immediateLine: "你拥有了计划，也拥有了一个无法开始的周末。",
        addFlags: ["todo-overflow"],
        addTraces: [{ type: "habit", text: "一张比项目本身更完整的任务表。" }],
      },
      {
        id: "pick-one-task",
        label: "只选一个任务",
        effects: { judgment: 7, stability: 5, agency: 4 },
        immediateLine: "任务表不壮观了，但你终于知道接下来 30 分钟做什么。",
        addFlags: ["one-task"],
        addTraces: [{ type: "habit", text: "把 37 个任务压成一个下一步。" }],
      },
    ],
  },
  {
    id: "awakening-name-before-product",
    phase: "awakening",
    title: "名字太好了",
    body: "你想到了一个特别适合放在官网首页的产品名。域名还没买，核心功能还没稳定，但你已经开始想 logo。",
    choices: [
      {
        id: "make-brand-first",
        label: "先做 logo 和官网",
        effects: { momentum: 6, judgment: -4, agency: -3 },
        immediateLine: "名字很完整，核心功能还没决定到底让用户做什么。",
        addFlags: ["brand-first"],
        addTraces: [
          { type: "reputation", text: "一个比功能更早成熟的产品名。" },
        ],
      },
      {
        id: "name-later",
        label: "先把功能跑稳",
        effects: { judgment: 6, stability: 4, momentum: -1 },
        immediateLine: "你暂时叫它“小工具”，它反而少了一点表演压力。",
        addFlags: ["function-first"],
        addTraces: [{ type: "work", text: "一个名字普通但能继续改的版本。" }],
      },
    ],
  },
  {
    id: "awakening-first-bug",
    phase: "awakening",
    title: "第一个报错",
    body: "演示版本跑了三次，第四次突然报错。错误信息很长，语气冷静得很伤人。",
    choices: [
      {
        id: "ask-fix-directly",
        label: "把报错丢给 AI",
        effects: { momentum: 5, judgment: -3, agency: -2 },
        immediateLine: "AI 给了你三个修法，其中两个和当前项目关系不大。",
        addFlags: ["blind-fix"],
        addTraces: [{ type: "work", text: "一次靠粘贴报错推进的修复。" }],
      },
      {
        id: "reproduce-bug",
        label: "先复现它",
        effects: { judgment: 9, stability: 5, momentum: -2 },
        immediateLine: "报错没有变可爱，但它终于有了触发条件。",
        addFlags: ["reproduced-bug"],
        addTraces: [{ type: "habit", text: "第一次为 bug 写下复现步骤。" }],
      },
    ],
  },
  {
    id: "awakening-hallucinated-api",
    phase: "awakening",
    title: "不存在的接口",
    body: "AI 建议你调用一个非常优雅的 API。文档里没有，搜索也没有，只有 AI 说得很坚定。",
    choices: [
      {
        id: "trust-api",
        label: "相信它见多识广",
        effects: { momentum: 4, judgment: -10, agency: -4 },
        immediateLine: "你花了 40 分钟寻找一个可能只存在于语气里的接口。",
        addFlags: ["hallucinated-api"],
        addTraces: [{ type: "work", text: "一次寻找不存在 API 的记录。" }],
      },
      {
        id: "check-docs",
        label: "先查官方文档",
        effects: { judgment: 10, agency: 5, momentum: -2 },
        immediateLine: "官方文档不会替你鼓掌，但至少真的存在。",
        addFlags: ["checked-docs"],
        addTraces: [{ type: "habit", text: "开始把 AI 的自信和事实分开。" }],
      },
    ],
  },
  {
    id: "awakening-env-file",
    phase: "awakening",
    title: "环境变量",
    body: "项目终于跑起来了，但 `.env.example` 还没写清楚。你知道现在不整理，以后每次部署都要重新猜一遍。",
    choices: [
      {
        id: "ignore-env",
        label: "先只管本机能跑",
        effects: { momentum: 6, stability: -7, judgment: -3 },
        immediateLine: "今天你快了十分钟，下次部署可能要花两小时排查配置。",
        addFlags: ["env-debt"],
        addTraces: [{ type: "work", text: "一个只有本人能启动的项目。" }],
      },
      {
        id: "write-env-example",
        label: "补一份示例",
        effects: { stability: 8, judgment: 5, momentum: -2 },
        immediateLine: "这不是热血时刻，但项目第一次可以交给别人启动。",
        addFlags: ["env-documented"],
        addTraces: [{ type: "work", text: "一份终于能看懂的环境变量说明。" }],
      },
    ],
  },
  {
    id: "awakening-landing-page",
    phase: "awakening",
    title: "落地页诱惑",
    body: "你还没有验证功能，但落地页模板已经在向你招手。它承诺 12 个区块、3 个动效和一堆很懂转化的标题。",
    choices: [
      {
        id: "build-landing",
        label: "先把页面做满",
        effects: { momentum: 7, judgment: -6, agency: -3 },
        immediateLine: "页面很完整，核心功能还没跟上。",
        addFlags: ["landing-first"],
        addTraces: [
          { type: "reputation", text: "一个功能还没稳但很会自我介绍的页面。" },
        ],
      },
      {
        id: "test-core-action",
        label: "先测核心动作",
        effects: { judgment: 9, stability: 4, momentum: -2 },
        immediateLine: "你没有漂亮首屏，但知道按钮点下去之后发生什么。",
        addFlags: ["core-action-tested"],
        addTraces: [{ type: "work", text: "一次绕过落地页的核心动作测试。" }],
      },
    ],
  },
  {
    id: "awakening-reinstall-night",
    phase: "awakening",
    title: "重装一切",
    body: "依赖冲突了。AI 建议你删掉缓存、重装依赖、升级框架。你不确定这会修问题，还是引入更多变化。",
    choices: [
      {
        id: "reinstall-all",
        label: "全部重装升级",
        effects: { momentum: 4, stability: -9, judgment: -4 },
        immediateLine: "错误信息换了一批，看起来更难判断了。",
        addFlags: ["reinstall-loop"],
        addTraces: [
          { type: "work", text: "一次从依赖冲突变成版本冒险的夜晚。" },
        ],
      },
      {
        id: "read-error-first",
        label: "先读错误来源",
        effects: { judgment: 8, stability: 5, agency: 3 },
        immediateLine: "你没有重装所有依赖，只修了一个包。",
        addFlags: ["read-error"],
        addTraces: [{ type: "habit", text: "开始在重装之前先读错误。" }],
      },
    ],
  },
  {
    id: "response-privacy-question",
    phase: "response",
    title: "隐私问题",
    body: "一个用户问：我的数据会去哪里？你突然意识到“只是个小工具”这句话不能当隐私政策。",
    choices: [
      {
        id: "handwave-privacy",
        label: "先含糊过去",
        effects: { momentum: 5, judgment: -7, stability: -8 },
        immediateLine: "对话继续了，但你的信任账户少了一点余额。",
        addFlags: ["privacy-handwave"],
        addTraces: [{ type: "relation", text: "一次被含糊回答的隐私问题。" }],
      },
      {
        id: "write-privacy-note",
        label: "写清楚数据流向",
        effects: { judgment: 8, stability: 7, momentum: -3 },
        immediateLine: "这段文字不性感，但用户终于知道自己在交给谁。",
        addFlags: ["privacy-written"],
        addTraces: [{ type: "work", text: "一份朴素但诚实的数据说明。" }],
      },
    ],
  },
  {
    id: "response-angry-user",
    phase: "response",
    title: "第一个差评",
    body: "用户说你的产品“看起来很炫酷，用起来很灾难”。这句话有点刺耳，也有点准确。",
    choices: [
      {
        id: "defend-product",
        label: "解释设计思路",
        effects: { agency: -2, judgment: -5, momentum: 3 },
        immediateLine: "你解释得很完整，用户的问题还是没有少走一步。",
        addFlags: ["defended-design"],
        addTraces: [{ type: "relation", text: "一次没有解决问题的设计解释。" }],
      },
      {
        id: "watch-user-use",
        label: "请他录屏操作",
        effects: { judgment: 10, stability: 4, agency: 3 },
        immediateLine: "你看到了他迷路的具体位置，刺耳变成了可修改。",
        addFlags: ["watched-user"],
        addTraces: [{ type: "relation", text: "一次真实用户的操作录屏。" }],
      },
    ],
  },
  {
    id: "response-community-demand",
    phase: "response",
    title: "社群邀请",
    body: "有人建议你建社群，说大家可以一起交流用法。你看到了活跃，也看到了每天 99+ 的消息。",
    choices: [
      {
        id: "open-community",
        label: "马上建群",
        effects: { momentum: 8, stability: -7, agency: -4 },
        immediateLine: "群很快热闹起来，产品路线图开始被表情包推动。",
        addFlags: ["community-opened"],
        addTraces: [
          { type: "reputation", text: "一个比产品更新更快的用户群。" },
        ],
      },
      {
        id: "collect-feedback-form",
        label: "先开反馈表",
        effects: { judgment: 6, stability: 6, momentum: -2 },
        immediateLine: "反馈少了点烟火气，但你终于能按问题排序。",
        addFlags: ["feedback-form"],
        addTraces: [{ type: "work", text: "一张不热闹但可整理的反馈表。" }],
      },
    ],
  },
  {
    id: "response-support-mail",
    phase: "response",
    title: "客服邮件",
    body: "你收到了第一封真正的客服邮件。对方没有夸你很厉害，只问为什么保存按钮没反应。",
    choices: [
      {
        id: "manual-support",
        label: "只回复这个用户",
        effects: { stability: -4, momentum: 4, judgment: -2 },
        immediateLine: "这个用户的问题解决了，下一个人还会遇到同一个保存按钮。",
        addFlags: ["manual-support"],
        addTraces: [
          { type: "relation", text: "第一封需要你认真回复的客服邮件。" },
        ],
      },
      {
        id: "fix-save-flow",
        label: "修掉保存问题",
        effects: { judgment: 7, stability: 6, momentum: -2 },
        immediateLine: "你少回了一封道歉邮件，多了一个真的能保存的按钮。",
        addFlags: ["save-fixed"],
        addTraces: [
          { type: "work", text: "一个终于不需要客服解释的保存流程。" },
        ],
      },
    ],
  },
  {
    id: "response-refactor-temptation",
    phase: "response",
    title: "重构诱惑",
    body: "代码开始变乱。AI 建议你重构成更优雅的架构，顺便换一个更现代的状态管理。",
    choices: [
      {
        id: "refactor-now",
        label: "趁早重构",
        effects: { judgment: 2, stability: -7, momentum: -5 },
        immediateLine: "架构图变漂亮了，两个用户问题还在原地等你。",
        addFlags: ["premature-refactor"],
        addTraces: [{ type: "work", text: "一次没有解决用户问题的重构。" }],
      },
      {
        id: "refactor-boundary",
        label: "只整理最痛的地方",
        effects: { judgment: 7, stability: 5, momentum: 2 },
        immediateLine: "你没有把房子推倒，只是修了漏水的那面墙。",
        addFlags: ["scoped-refactor"],
        addTraces: [{ type: "work", text: "一次有边界的局部重构。" }],
      },
    ],
  },
  {
    id: "response-analytics-weird",
    phase: "response",
    title: "数据很奇怪",
    body: "数据面板显示很多人点了开始，却很少人完成。你不知道是产品太难，还是按钮位置太不明显。",
    choices: [
      {
        id: "add-more-tracking",
        label: "先加更多埋点",
        effects: { judgment: 2, momentum: 3, stability: -3 },
        immediateLine: "你拥有了更多数字，但问题还没有拥有名字。",
        addFlags: ["tracking-more"],
        addTraces: [
          { type: "work", text: "一块信息更多但答案更少的数据面板。" },
        ],
      },
      {
        id: "watch-session",
        label: "看一次真实路径",
        effects: { judgment: 9, stability: 3, agency: 3 },
        immediateLine: "你看到用户在第一屏就犹豫了，数字终于有了画面。",
        addFlags: ["watched-session"],
        addTraces: [{ type: "relation", text: "一次把数据还原成人的观察。" }],
      },
    ],
  },
  {
    id: "response-copycat",
    phase: "response",
    title: "同类产品出现",
    body: "一个相似产品突然火了。它更漂亮，介绍更短，评论区有人说“终于有人做了这个”。",
    choices: [
      {
        id: "panic-copy",
        label: "立刻照着补功能",
        effects: { momentum: 7, agency: -7, judgment: -5 },
        immediateLine: "你跑得更快了，只是方向由别人替你校准。",
        addFlags: ["copycat-panic"],
        addTraces: [
          { type: "reputation", text: "一次被同类产品推着走的更新。" },
        ],
      },
      {
        id: "compare-position",
        label: "重新确认定位",
        effects: { judgment: 8, agency: 7, momentum: -2 },
        immediateLine: "你没有假装不紧张，但至少没有把自己改丢。",
        addFlags: ["position-checked"],
        addTraces: [{ type: "work", text: "一份写清楚差异的定位笔记。" }],
      },
    ],
  },
  {
    id: "response-one-paying-user",
    phase: "response",
    title: "第一笔钱",
    body: "有人真的付费了。金额不大，但你盯着支付成功的提示看了好几秒。",
    choices: [
      {
        id: "declare-validation",
        label: "立刻晒支付截图",
        effects: { momentum: 9, judgment: -5, stability: -3 },
        immediateLine: "你把截图放大了三次，商业模式暂时还没跟上。",
        addFlags: ["paid-users", "validation-declared"],
        addTraces: [
          { type: "cost", text: "第一笔收入和一张被反复截图的支付记录。" },
        ],
      },
      {
        id: "ask-why-paid",
        label: "问他为什么付费",
        effects: { judgment: 9, stability: 5, agency: 3 },
        immediateLine: "钱没有变多，但你知道它为什么出现了。",
        addFlags: ["paid-users", "asked-why-paid"],
        addTraces: [
          { type: "relation", text: "一次关于为什么愿意付费的追问。" },
        ],
      },
    ],
  },
  {
    id: "response-weekly-changelog",
    phase: "response",
    title: "周更新",
    body: "你准备发一条周更新。你可以写“本周重大升级”，也可以老实列出修了哪些小问题。",
    choices: [
      {
        id: "big-update-copy",
        label: "写得更像大更新",
        effects: { momentum: 6, judgment: -4, agency: -2 },
        immediateLine: "更新看起来很大，用户打开后发现主要是按钮不再乱跳。",
        addFlags: ["launch-tone"],
        addTraces: [
          { type: "reputation", text: "一条比实际更新更激昂的公告。" },
        ],
      },
      {
        id: "plain-changelog",
        label: "老实写修了什么",
        effects: { judgment: 5, stability: 5, agency: 3 },
        immediateLine: "公告没有燃起来，但用户知道你真的在修东西。",
        addFlags: ["plain-changelog"],
        addTraces: [{ type: "reputation", text: "一份朴素但可信的周更新。" }],
      },
    ],
  },
  {
    id: "identity-refund",
    phase: "identity",
    title: "退款请求",
    body: "有人申请退款，理由写得很短：和预期不一样。你突然意识到预期也是产品的一部分。",
    choices: [
      {
        id: "argue-refund",
        label: "解释它其实能用",
        effects: { agency: -3, judgment: -5, stability: -4 },
        immediateLine: "解释没有挽回这笔钱，也没有修正那个预期。",
        addFlags: ["refund-argued"],
        addTraces: [
          { type: "relation", text: "一次把退款当辩论题处理的经历。" },
        ],
      },
      {
        id: "refund-and-fix-copy",
        label: "退款并改说明",
        effects: { judgment: 8, stability: 5, agency: 3 },
        immediateLine: "你少了一笔钱，多了一句不会误导人的说明。",
        addFlags: ["refund-learned"],
        addTraces: [{ type: "cost", text: "一次退款和一次更诚实的产品说明。" }],
      },
    ],
  },
  {
    id: "identity-investor-call",
    phase: "identity",
    title: "投资人来信",
    body: "有人约你聊聊“更大的可能性”。你还没想好下个月怎么活，但已经有人问三年愿景。",
    choices: [
      {
        id: "pitch-big",
        label: "讲一个大故事",
        effects: { momentum: 8, agency: -4, judgment: -4 },
        immediateLine: "愿景听起来很远大，连你自己都需要追上它。",
        addFlags: ["big-vision"],
        addTraces: [
          { type: "reputation", text: "一次把小工具讲成大机会的通话。" },
        ],
      },
      {
        id: "say-current-truth",
        label: "先讲当前真相",
        effects: { judgment: 8, agency: 5, stability: 3 },
        immediateLine: "你没有把故事讲满，但保住了和现实的连接。",
        addFlags: ["truthful-call"],
        addTraces: [{ type: "relation", text: "一次没有过度包装的外部沟通。" }],
      },
    ],
  },
  {
    id: "identity-paid-sharing",
    phase: "identity",
    title: "付费分享邀请",
    body: "有人邀请你做一期“普通人如何用 AI 改变命运”的付费分享。题目很懂传播，你的产品还在修保存按钮。",
    choices: [
      {
        id: "accept-course",
        label: "先接下分享",
        effects: { momentum: 8, agency: -6, judgment: -5 },
        immediateLine: "分享题目已经定了，保存按钮还在后台排队。",
        addFlags: ["public-methodology", "course-accepted"],
        addTraces: [
          { type: "reputation", text: "一次比产品更快商业化的分享邀请。" },
        ],
      },
      {
        id: "share-after-proof",
        label: "等验证再讲",
        effects: { judgment: 7, stability: 5, agency: 4, momentum: -3 },
        immediateLine: "你少赚了一次快钱，也少讲了一次还没发生的成功。",
        addFlags: ["teach-later"],
        addTraces: [{ type: "habit", text: "一次把表达欲延后的选择。" }],
      },
    ],
  },
  {
    id: "identity-roadmap-vote",
    phase: "identity",
    title: "路线图投票",
    body: "用户开始投票要功能。票数最高的是一个很热闹、很难维护、和你原始方向关系不大的东西。",
    choices: [
      {
        id: "follow-vote",
        label: "跟着票数走",
        effects: { momentum: 7, agency: -8, judgment: -4 },
        immediateLine: "你尊重了民意，也把方向盘交给了最响亮的需求。",
        addFlags: ["roadmap-voted"],
        addTraces: [{ type: "relation", text: "一次由票数推动的路线图偏航。" }],
      },
      {
        id: "explain-no",
        label: "解释为什么不做",
        effects: { agency: 8, judgment: 6, stability: 3, momentum: -2 },
        immediateLine: "不是所有人都满意，但产品没有被投票带走。",
        addFlags: ["said-no-roadmap"],
        addTraces: [{ type: "relation", text: "一次清楚但不讨好的拒绝。" }],
      },
    ],
  },
  {
    id: "identity-delegate-support",
    phase: "identity",
    title: "支持工作外包",
    body: "你可以把客服、文档和常见问题交给 AI 处理。它能很快回复，只是偶尔会把不存在的功能说得很熟。",
    choices: [
      {
        id: "delegate-all-support",
        label: "全部交给 AI 回复",
        effects: { momentum: 8, agency: -8, judgment: -5 },
        immediateLine: "回复速度上去了，它偶尔也把没上线的功能说成已上线。",
        addFlags: ["auto-everything", "support-delegated"],
        addTraces: [
          { type: "relation", text: "一套回复很快但需要抽查的自动客服。" },
        ],
      },
      {
        id: "draft-then-review",
        label: "让它起草，你审核",
        effects: { judgment: 6, agency: 5, stability: 4 },
        immediateLine: "你没有被客服吞掉，也没有把用户交给未经确认的回答。",
        addFlags: ["support-reviewed"],
        addTraces: [
          { type: "habit", text: "一套自动起草、人工确认的支持流程。" },
        ],
      },
    ],
  },
  {
    id: "identity-delete-feature",
    phase: "identity",
    title: "删除功能",
    body: "有个功能很酷，但没人用。它每周都制造小问题，还在首页占着一块很自信的位置。",
    choices: [
      {
        id: "keep-cool-feature",
        label: "先留着，万一呢",
        effects: { momentum: 3, judgment: -6, stability: -5 },
        immediateLine: "它继续证明你很有想象力，也继续消耗维护时间。",
        addFlags: ["kept-cool-feature"],
        addTraces: [{ type: "work", text: "一个很酷但没人用的首页功能。" }],
      },
      {
        id: "delete-cool-feature",
        label: "删掉它",
        effects: { judgment: 8, stability: 7, agency: 4 },
        immediateLine: "页面少了一块炫耀，多了一点清楚。",
        addFlags: ["deleted-feature"],
        addTraces: [{ type: "work", text: "一次让产品变小也变清楚的删除。" }],
      },
    ],
  },
  {
    id: "identity-tax-invoice",
    phase: "identity",
    title: "发票和税",
    body: "收入开始变得真实，于是发票、税务和合同也开始变得真实。你怀念那个只需要改按钮的下午。",
    choices: [
      {
        id: "avoid-admin",
        label: "先拖一拖",
        effects: { momentum: 4, stability: -8, judgment: -4 },
        immediateLine: "你暂时继续创造，现实也暂时记账。",
        addFlags: ["admin-delayed"],
        addTraces: [{ type: "cost", text: "一摞被推迟处理的现实文件。" }],
      },
      {
        id: "admin-day",
        label: "安排一天处理",
        effects: { stability: 8, judgment: 5, momentum: -4 },
        immediateLine: "这一天不够热闹，但让项目更能继续下去。",
        addFlags: ["admin-handled"],
        addTraces: [{ type: "cost", text: "一次不浪漫但必要的行政日。" }],
      },
    ],
  },
  {
    id: "identity-handoff-docs",
    phase: "identity",
    title: "交接文档",
    body: "有人愿意帮你一起做。你突然发现，项目很多地方只存在于你的脑子和聊天记录里。",
    choices: [
      {
        id: "explain-live",
        label: "开会口头讲",
        effects: { momentum: 5, stability: -4, judgment: -2 },
        immediateLine:
          "你讲了很多，对方记了很多，最后还是不知道从哪个文件开始。",
        addFlags: ["oral-handoff"],
        addTraces: [
          { type: "relation", text: "一次很努力但难复用的口头交接。" },
        ],
      },
      {
        id: "write-handoff",
        label: "写最小文档",
        effects: { judgment: 6, stability: 7, agency: 3, momentum: -3 },
        immediateLine: "文档不华丽，但第一次有人能不靠读心加入项目。",
        addFlags: ["handoff-docs"],
        addTraces: [{ type: "work", text: "一份能让别人接手的最小文档。" }],
      },
    ],
  },
];
